// 内置提示词场景包（R74，F7 收尾）：开箱即用的模板集，覆盖常用语入门、个人信息
// （地址 / 邮箱 / 联系方式）与定位三大场景（客服模板 / AI 提示词库 / 研发写作常用件），
// 演示 {{xlc:ask:…}} 变量与 {{xlc:cursor}} 光标落点。
// 格式与 buildMarkdownExport 一致（xlc-pack 清单 + xlc-item 元数据），导入走既有 parseMarkdownPack
// → 策略对话框；ID 固定，重复导入由「跳过重复」天然幂等。
// 内容均为通用模板正文（无第三方版权材料）；变量语法为插件自有。

export const PROMPT_PACK_NAME = "提示词场景包";

export const PROMPT_PACK_MD = [
    "<!-- xlc-pack",
    `name: ${PROMPT_PACK_NAME}`,
    "items: 16",
    "vars: 客户名称,补偿比例,工单号,跟进日期,客户昵称,目标读者,编程语言,本周主题,会议主题,表名,姓名,职位,公司名称,邮箱,手机号,收件人,主题,省市区,详细地址,邮编,备注",
    "-->",
    "# 提示词场景包",
    "",
    "> 小驴常用（内测版）内置模板集：使用说明 / 地址 / 邮箱 / 联系方式 / 客服回复 / AI 提示词 / 研发写作。导入后即为真实思源块，可自由修改。",

    // ---- 入门与个人信息 ----
    "## 使用说明：三步开始",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000011",
    "type: markdown",
    "tags: 入门,规则",
    "category: 使用说明",
    "source-type: external",
    "-->",
    "# 小驴常用怎么用",
    "",
    "1. **先保存**：在编辑器选中文本，使用右键「保存为常用条目」；也可以从剪贴板快速捕获，或在面板中点「新建」。",
    "2. **再调用**：打开面板搜索标题、正文、标签或分类，按 Enter 插入，按 Ctrl/⌘+Enter 复制；有 `｛｛xlc:ask:字段｝｝` 的模板会在插入前询问一次。",
    "3. **持续整理**：用标签和分类区分场景，收藏高频条目；条目正文仍是库文档中的真实块，可在思源中直接编辑。",
    "",
    "**模板规则**",
    "- `｛｛xlc:ask:字段｝｝` = 插入时填写；`｛｛xlc:ask:字段|选项A,选项B｝｝` = 下拉选择（本说明用全角括号展示语法，实际模板请改为半角）。填写内容只用于本次插入，不会回写模板。",
    "- `｛｛xlc:date｝｝`、`｛｛xlc:clipboard｝｝` 等动态占位符只在插入/复制时展开，模板原文始终保留。",
    "- 推荐分类：客服、邮箱、地址、联系方式、提示词、写作、开发；分类名称可以按自己的工作流修改。",
    "",
    "**从哪里开始**：先导入本包中的「邮箱签名」「收件地址」或「联系人卡片」，把示例字段替换为自己的字段，再复制成个人条目。",

    "## 邮箱签名",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000012",
    "type: text",
    "tags: 邮箱,签名",
    "category: 邮箱",
    "source-type: external",
    "-->",
    "{{xlc:ask:姓名}}｜{{xlc:ask:职位}}",
    "{{xlc:ask:公司名称}}",
    "邮箱：{{xlc:ask:邮箱}}",
    "电话：{{xlc:ask:手机号}}{{xlc:cursor}}",

    "## 邮件回复开头",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000013",
    "type: markdown",
    "tags: 邮箱,回复",
    "category: 邮箱",
    "source-type: external",
    "-->",
    "主题：{{xlc:ask:主题}}",
    "",
    "{{xlc:ask:收件人}} 您好：",
    "",
    "感谢来信。关于您提到的事项，我们会在 __时间__ 前回复；如有补充信息，欢迎直接回复本邮件。",
    "",
    "祝好！{{xlc:cursor}}",

    "## 收件地址",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000014",
    "type: text",
    "tags: 地址,快递",
    "category: 地址",
    "source-type: external",
    "-->",
    "收件人：{{xlc:ask:收件人}}",
    "地址：{{xlc:ask:省市区}} {{xlc:ask:详细地址}}",
    "邮编：{{xlc:ask:邮编}}",
    "电话：{{xlc:ask:手机号}}{{xlc:cursor}}",

    "## 联系人卡片",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000015",
    "type: markdown",
    "tags: 联系方式,联系人",
    "category: 联系方式",
    "source-type: external",
    "-->",
    "**{{xlc:ask:姓名}}**",
    "- 手机：{{xlc:ask:手机号}}",
    "- 邮箱：{{xlc:ask:邮箱}}",
    "- 备注：{{xlc:ask:备注|textarea}}{{xlc:cursor}}",

    "## 地址标签",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000016",
    "type: text",
    "tags: 地址,标签",
    "category: 地址",
    "source-type: external",
    "-->",
    "{{xlc:ask:收件人}} / {{xlc:ask:省市区}} / {{xlc:ask:详细地址}} / {{xlc:ask:手机号}}",

    // ---- 场景① 客服模板 ----
    "## 延期致歉回复",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000001",
    "type: markdown",
    "tags: 客服,模板",
    "category: 客服",
    "source-type: external",
    "-->",
    "尊敬的 {{xlc:ask:客户名称}}：",
    "",
    "关于本期交付计划的调整，我们深表歉意。主要原因为 __原因__，目前进度已达 __百分比__，预计推迟 __天数__ 个工作日。",
    "",
    "为弥补影响，我们提供以下补偿：",
    "1. 本期服务费减免 {{xlc:ask:补偿比例|5%,10%,自定义}}；",
    "2. 上线后 48 小时专属值守；",
    "3. 下期迭代优先排入贵方需求。",
    "",
    "再次感谢理解与支持，有任何问题随时联系我。{{xlc:cursor}}",

    "## 工单进度跟进",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000002",
    "type: markdown",
    "tags: 客服,跟进",
    "category: 客服",
    "source-type: external",
    "-->",
    "{{xlc:ask:客户名称}} 您好：",
    "",
    "您的工单 {{xlc:ask:工单号}} 当前状态：__当前状态__。",
    "预计完成时间：{{xlc:ask:跟进日期|date}}。期间有任何补充信息请直接回复本消息。",
    "",
    "感谢您的耐心等待。{{xlc:cursor}}",

    "## 好评感谢回复",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000003",
    "type: text",
    "tags: 客服,回复",
    "category: 客服",
    "source-type: external",
    "-->",
    "感谢 {{xlc:ask:客户昵称}} 的认可与支持！您的鼓励是我们前进的动力，如再次光临有任何问题，随时联系我。祝生活愉快！{{xlc:cursor}}",

    // ---- 场景② AI 提示词库 ----
    "## 文章润色提示词",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000004",
    "type: text",
    "tags: AI,提示词",
    "category: 提示词",
    "source-type: external",
    "-->",
    "你是资深编辑。请润色以下文章，面向 {{xlc:ask:目标读者|普通读者,专业读者}}：",
    "保持原意与结构，仅提升流畅度与表达力；不改写事实，不新增内容。",
    "输出润色后的全文：",
    "",
    "{{xlc:clipboard}}{{xlc:cursor}}",

    "## 代码审查提示词",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000005",
    "type: text",
    "tags: AI,提示词,开发",
    "category: 提示词",
    "source-type: external",
    "-->",
    "你是 {{xlc:ask:编程语言|TypeScript,Python,Go}} 资深工程师，请审查以下代码，按严重度输出：",
    "1. 正确性问题（会出错的地方）",
    "2. 安全隐患",
    "3. 可读性与维护性建议",
    "仅列问题与修改建议，不重写全文：",
    "",
    "{{xlc:clipboard}}{{xlc:cursor}}",

    "## 会议要点提炼提示词",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000006",
    "type: text",
    "tags: AI,提示词",
    "category: 提示词",
    "source-type: external",
    "-->",
    "请把以下会议记录提炼为要点：结论 / 待办（负责人+截止时间）/ 风险三类，每条一行：",
    "",
    "{{xlc:clipboard}}{{xlc:cursor}}",

    // ---- 场景③ 研发写作常用件 ----
    "## 周报开头",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000007",
    "type: markdown",
    "tags: 写作,周报",
    "category: 写作",
    "source-type: external",
    "-->",
    "本周围绕 {{xlc:ask:本周主题}} 推进，关键进展：",
    "",
    "1. __事项__（状态：__进度__）",
    "2. __事项__（状态：__进度__）",
    "",
    "风险与依赖：{{xlc:cursor}}",

    "## 会议纪要骨架",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000008",
    "type: markdown",
    "tags: 写作,会议",
    "category: 写作",
    "source-type: external",
    "-->",
    "# {{xlc:ask:会议主题}} · 会议纪要（{{xlc:date}}）",
    "",
    "## 结论",
    "- {{xlc:cursor}}",
    "## 待办",
    "- [ ] __事项__（负责人：__ / 截止：__）",
    "## 风险",
    "- ",

    "## 日计划模板",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000009",
    "type: markdown",
    "tags: 写作,计划",
    "category: 写作",
    "source-type: external",
    "-->",
    "## 今日三件事（{{xlc:date}}）",
    "",
    "1. {{xlc:cursor}}",
    "2. ",
    "3. ",
    "## 留白（应对突发）",
    "- ",

    "## SQL 分页查询",
    "",
    "<!-- xlc-item",
    "id: xlc-pack00000010",
    "type: code",
    "tags: 开发,SQL",
    "category: 开发",
    "source-type: external",
    "-->",
    "```sql",
    "SELECT * FROM {{xlc:ask:表名}}",
    "WHERE status = 'published'",
    "ORDER BY updated_at DESC",
    "LIMIT 20 OFFSET 40;",
    "```",
].join("\n");
